apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamic-pricing
  labels:
    app: dynamic-pricing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamic-pricing
  template:
    metadata:
      labels:
        app: dynamic-pricing
    spec:
      containers:
      - name: dynamic-pricing
        image: REGION-docker.pkg.dev/PROJECT_ID/IMAGE_REPO/IMAGE_NAME:latest
        ports:
        - containerPort: 443
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: dynamic-pricing
  labels:
    run: dynamic-pricing
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  selector:
    app: dynamic-pricing
  type: LoadBalancer
