### STAGE 1: Build ###
FROM node:16.13.1 as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
RUN npm run export

### STAGE 2: Run ###
FROM nginx:1.17.1-alpine
COPY nginx.conf /etc/nginx/nginx.conf

COPY cert/pertaminalubricants.com.pem /etc/nginx/ssl/pertaminalubricants.com.pem
COPY cert/SSLCert2023.key /etc/nginx/ssl/SSLCert2023.key

EXPOSE 80
EXPOSE 443

COPY --from=build /app/out /usr/share/nginx/html